Publish gripper joint state from hardware interface
sbgisen/xarm_ros pull request #14
Opened 2023-01-20 04:46 UTC by Tacha-S

## Summary

- fix #13 

## Detail

## Impact

## Test

  

## Attention

2023-01-20 08:59 UTC, jsupratman13 reviewed
add_gripperのパラメータがtrue/false関係なくgripper action serverが立ち上がるけどいいの？

2023-01-20 09:07 UTC, Tacha-S commented
gripperがない場合action serverも立ち上がらないようにしておきます。

2023-01-20 10:16 UTC, jsupratman13 requested changes

2023-01-20 10:16 UTC, jsupratman13 commented on xarm_api/src/xarm_driver.cpp
>          gripper_joint_state_msg_.name[5] = "right_inner_knuckle_joint";
見逃していた．
gripper_joint_stateトピックに渡すnameは定数でいいの？

2023-01-23 00:14 UTC, Tacha-S commented on xarm_api/src/xarm_driver.cpp
>          gripper_joint_state_msg_.name[5] = "right_inner_knuckle_joint";
それはxarm_driverのノード単体で起動したときのもので、hardware_interface経由だと
https://github.com/sbgisen/xarm_ros/pull/14/files#diff-612d68fc4ba50500b40d16b9f320b6bdb645b437917ccfb86ff5f565539aa935R125-R131
ここでparameterから読み込んでいます。

2023-01-23 00:47 UTC, jsupratman13 commented on xarm_api/src/xarm_driver.cpp
>          gripper_joint_state_msg_.name[5] = "right_inner_knuckle_joint";
JointStateHandleに入る`jnt_names_` はparameterでジョイント名は変更できるけど，rostopicでpublishする時の`gripper_joint_state_msgs_`のジョイント名はparameterで（今のままだと）変更できないと思うけど違う？

2023-01-23 00:54 UTC, Tacha-S commented on xarm_api/src/xarm_driver.cpp
>          gripper_joint_state_msg_.name[5] = "right_inner_knuckle_joint";
xarm_driverが独自でjoint_statesをpublishする場合は`gripper_joint_state_msgs_` を使うのでそうですが、そんなhardware interfaceを使用しない運用はしないのでそこの変更は無駄な労力だと思います。

自分の認識が正しければ、hardware interfaceが出すjoint_statesはregisterHandleで登録されたジョイント名でpublishされるはずです。そのため、getGripperJointStates()でmessageのまま受け取っていますが、更新しているのは各ジョイントのpositionの値だけなのでparameterのジョイント名でpublishされると思います。

2023-01-23 01:30 UTC, jsupratman13 commented on xarm_api/src/xarm_driver.cpp
>          gripper_joint_state_msg_.name[5] = "right_inner_knuckle_joint";
ok

2023-01-23 01:31 UTC, jsupratman13 approved these changes

2023-01-23 01:31 UTC, merged